[unstable]
profile-rustflags = true
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem", "panic_immediate_abort"]

[build]
rustflags = ["-Cpanic=abort"]
target = "x86_64-unknown-linux-none"

[profile.release]
rustflags = [
    "-C",
    "linker-plugin-lto",
    "-C",
    "link-arg=-Wl,-z,pack-relative-relocs",
    "-C",
    "link-arg=-Wl,-O1",
    "-C",
    "link-arg=-Wl,--gc-sections",
    "-C",
    "link-arg=-Wl,--as-needed",
    "-C",
    "link-arg=-Wl,-z,now",
    "-C",
    "link-arg=-Wl,-z,relro",
]